/*
 * Howdy!
 *
 * This file is automatically generated on a new build.
 * You should not change it manually!
 */

#pragma once

#define TH_GIT_REV "07940ae-WORKING"
#define TH_GIT_TAG ""
#define TH_GIT_BRANCH "master"

#define TH_BUILD_DATE "02/07/2022"
#define TH_BUILD_DATE_UTC "02/07/2022"
#define TH_BUILD_TIME "11:21:59"
#define TH_BUILD_TIME_UTC "11:21:59"
