/*
 * Howdy!
 *
 * This file is automatically generated on a new build.
 * You should not change it manually!
 */

#pragma once

#define TH_GIT_REV "d9ce7c5-WORKING"
#define TH_GIT_TAG ""
#define TH_GIT_BRANCH "master"

#define TH_BUILD_DATE "02/07/2022"
#define TH_BUILD_DATE_UTC "02/07/2022"
#define TH_BUILD_TIME "12:10:44"
#define TH_BUILD_TIME_UTC "12:10:44"
